### ISSUE TITLE
Transformers compatibility issue

### ISSUE THREAD

**Issue by alokkrsahu** [salesforce/GeDi#19]
Can we not run the GeDI on current transformers version 4.30.0?

I tried running **run_generation.sh** file but getting error from transformer.file_utils?

Can anyone suggest how to fix this code, or redirect me to any new version of the code, or new technique, please?

Any help would be appreciated!!

Thanks in advance!

Thanks and regards,
Alok

**Comment by gWeiXP** [comment]
Transformers version 2.8.0 is OK, any version > 3 will not run successfully. 
(A lot of other models, version 3 only works, get angry)

**Comment by alokkrsahu** [comment]
Thank you for your response 🙏
