### ISSUE TITLE
num_return_sequences parameter not working in model.generate function.

### ISSUE THREAD

**Issue by rishabhjain** [salesforce/GeDi#5]
I have been trying to get a look at different generated sequences from same prompt and topic. This can usually be done by setting `num_return_sequences` parameter > 1. Is it possible to use this parameters when GeDi is controlling GPT2?

Is there any other way to look at multiple generated outputs from same set of prompt and topic?

**Comment by janleemark** [comment]
I also encountered this problem, have you to solve it？
